/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRegisterRouteImport } from './routes/_app.register'
import { Route as AppRatingRouteImport } from './routes/_app.rating'
import { Route as AppEvaluateRouteImport } from './routes/_app.evaluate'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppRatingRoute = AppRatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluateRoute = AppEvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/evaluate': typeof AppEvaluateRoute
  '/rating': typeof AppRatingRoute
  '/register': typeof AppRegisterRoute
}
export interface FileRoutesByTo {
  '/evaluate': typeof AppEvaluateRoute
  '/rating': typeof AppRatingRoute
  '/register': typeof AppRegisterRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/evaluate': typeof AppEvaluateRoute
  '/_app/rating': typeof AppRatingRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evaluate' | '/rating' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/evaluate' | '/rating' | '/register' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/evaluate'
    | '/_app/rating'
    | '/_app/register'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rating': {
      id: '/_app/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof AppRatingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evaluate': {
      id: '/_app/evaluate'
      path: '/evaluate'
      fullPath: '/evaluate'
      preLoaderRoute: typeof AppEvaluateRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEvaluateRoute: typeof AppEvaluateRoute
  AppRatingRoute: typeof AppRatingRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEvaluateRoute: AppEvaluateRoute,
  AppRatingRoute: AppRatingRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
